### PR TITLE
Bumps axios from 0.18.0 to 0.19.0

### PR DESCRIPTION
**Pull request by ddompe**
New axios version provides support for no_proxy variable and solves
the problem outlined at https://github.com/eclipse/che/issues/14676

### CODE REVIEW

**Comment by evidolob** [comment]
@ddompe You need to sight ECA to let us merge this PR.
See: https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions and https://www.eclipse.org/legal/ECA.php

**Comment by ddompe** [comment]
Thanks @evidolob, I’m aware. I already put the paperwork inside the company I work for, to get the legal approval to contribute. Hope to get some answer this week and sign.

**Comment by akurinnoy** [comment]
I created CQ for axios 0.19.0
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21114

**Comment by evidolob** [comment]
@ddompe Would you mind if we create another PR instead of yours? We really need this ASAP.

**Comment by ddompe** [comment]
Not at all, closing this one! Thanks

**Pull request closed without merging**
